### ISSUE TITLE
Unable to build app prod

### ISSUE THREAD

**Issue by devsgtech** [tjoskar/ng-lazyload-image#451] opened 2020-03-25 17:04 UTC
![image](https://user-images.githubusercontent.com/46337791/77564360-9b962d80-6ee8-11ea-92ed-5fc0bd9c9e14.png)

> ERROR in ./node_modules/ng-lazyload-image/fesm2015/ng-lazyload-image.js
Module build failed (from ./node_modules/@angular-devkit/build-optimizer/src/build-optimizer/webpack-loader.js):
TypeError: Cannot read property 'kind' of undefined
    at isAngularDecoratorMetadataExpression (/Users/apple/Desktop/IonicProjects/Synchron/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:265:35)
    at checkNodeForDecorators (/Users/apple/Desktop/IonicProjects/Synchron/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:77:21)
    at visitNodes (/Users/apple/Desktop/IonicProjects/Synchron/node_modules/typescript/lib/typescript.js:16514:30)
    at Object.forEachChild (/Users/apple/Desktop/IonicProjects/Synchron/node_modules/typescript/lib/typescript.js:16740:24)
    at checkNodeForDecorators (/Users/apple/Desktop/IonicProjects/Synchron/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:68:31)
    at visitNode (/Users/apple/Desktop/IonicProjects/Synchron/node_modules/typescript/lib/typescript.js:16505:24)
    at Object.forEachChild (/Users/apple/Desktop/IonicProjects/Synchron/node_modules/typescript/lib/typescript.js:16635:21)
    at checkNodeForDecorators (/Users/apple/Desktop/IonicProjects/Synchron/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:68:31)
    at visitNode (/Users/apple/Desktop/IonicProjects/Synchron/node_modules/typescript/lib/typescript.js:16505:24)
    at Object.forEachChild (/Users/apple/Desktop/IonicProjects/Synchron/node_modules/typescript/lib/typescript.js:16703:24)
    at checkNodeForDecorators (/Users/apple/Desktop/IonicProjects/Synchron/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:68:31)
    at visitNode (/Users/apple/Desktop/IonicProjects/Synchron/node_modules/typescript/lib/typescript.js:16505:24)
    at Object.forEachChild (/Users/apple/Desktop/IonicProjects/Synchron/node_modules/typescript/lib/typescript.js:16692:24)
    at checkNodeForDecorators (/Users/apple/Desktop/IonicProjects/Synchron/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:68:31)
    at visitNode (/Users/apple/Desktop/IonicProjects/Synchron/node_modules/typescript/lib/typescript.js:16505:24)
    at Object.forEachChild (/Users/apple/Desktop/IonicProjects/Synchron/node_modules/typescript/lib/typescript.js:16599:21)
[ERROR] An error occurred while running subprocess ng.
        

> 

**package.json file code below**
`{
  "name": "ABC",
  "version": "0.0.1",
  "author": "Ionic Framework",
  "homepage": "https://ionicframework.com/",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "ios-l-sim": "ionic cordova run ios -l",
    "ios-l-device": "ionic cordova run ios -l --address=0.0.0.0",
    "ios-l-device-log": "ionic cordova run ios -l --address=0.0.0.0 --consolelogs",
    "ios-build-pro": "ionic cordova build ios --prod",
    "android-l-em": "ionic cordova run android -l",
    "android-l-device": "ionic cordova run android -l",
    "android-l-device-log": "ionic cordova run android -l --consolelogs",
    "android-build-pro-release": "ionic cordova build android --prod --release"
  },
  "private": true,
  "dependencies": {
    "@agm/core": "^1.1.0",
    "@angular/animations": "^8.2.14",
    "@angular/common": "~8.1.2",
    "@angular/core": "~8.1.2",
    "@angular/fire": "^5.4.2",
    "@angular/forms": "~8.1.2",
    "@angular/platform-browser": "~8.1.2",
    "@angular/platform-browser-dynamic": "~8.1.2",
    "@angular/router": "~8.1.2",
    "@firebase/database": "^0.5.24",
    "@ionic-native/android-permissions": "^5.23.0",
    "@ionic-native/app-version": "^5.23.0",
    "@ionic-native/camera": "^5.23.0",
    "@ionic-native/chooser": "^5.23.0",
    "@ionic-native/core": "^5.23.0",
    "@ionic-native/file": "^5.23.0",
    "@ionic-native/file-opener": "^5.23.0",
    "@ionic-native/file-transfer": "^5.23.0",
    "@ionic-native/image-picker": "^5.23.0",
    "@ionic-native/in-app-browser": "^5.23.0",
    "@ionic-native/keyboard": "^5.23.0",
    "@ionic-native/network": "^5.23.0",
    "@ionic-native/onesignal": "^5.23.0",
    "@ionic-native/photo-viewer": "^5.23.0",
    "@ionic-native/splash-screen": "^5.23.0",
    "@ionic-native/status-bar": "^5.23.0",
    "@ionic-native/toast": "^5.23.0",
    "@ionic/angular": "^4.7.1",
    "@ionic/storage": "^2.2.0",
    "angular-animations": "0.0.10",
    "com-sarriaroman-photoviewer": "^1.2.4",
    "cordova-android": "8.1.0",
    "cordova-ios": "5.1.1",
    "cordova-plugin-add-swift-support": "^2.0.2",
    "cordova-plugin-android-permissions": "^1.0.2",
    "cordova-plugin-app-version": "^0.1.9",
    "cordova-plugin-camera": "^4.1.0",
    "cordova-plugin-chooser": "^1.2.6",
    "cordova-plugin-file": "^6.0.2",
    "cordova-plugin-file-opener2": "^3.0.0",
    "cordova-plugin-file-transfer": "^1.7.1",
    "cordova-plugin-inappbrowser": "^3.2.0",
    "cordova-plugin-ionic-keyboard": "^2.2.0",
    "cordova-plugin-network-information": "^2.0.2",
    "cordova-plugin-telerik-imagepicker": "^2.3.3",
    "cordova-plugin-x-toast": "^2.7.2",
    "core-js": "^2.5.4",
    "firebase": "^7.12.0",
    "jsbarcode": "^3.11.0",
    "moment": "^2.24.0",
    "moment-timezone": "^0.5.28",
    "ng-lazyload-image": "^7.1.0",
    "onesignal-cordova-plugin": "^2.8.4",
    "rxjs": "~6.5.1",
    "sweetalert2": "^9.10.6",
    "tslib": "^1.11.1",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/architect": "~0.801.2",
    "@angular-devkit/build-angular": "~0.801.2",
    "@angular-devkit/core": "~8.1.2",
    "@angular-devkit/schematics": "~8.1.2",
    "@angular/cli": "~8.1.2",
    "@angular/compiler": "~8.1.2",
    "@angular/compiler-cli": "~8.1.2",
    "@angular/language-service": "~8.1.2",
    "@ionic/angular-toolkit": "^2.2.0",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "^5.0.0",
    "cordova-plugin-device": "^2.0.3",
    "cordova-plugin-ionic-webview": "^4.1.3",
    "cordova-plugin-splashscreen": "^5.0.3",
    "cordova-plugin-statusbar": "^2.4.3",
    "cordova-plugin-whitelist": "^1.3.4",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.5.3",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.15.0",
    "typescript": "~3.4.3"
  },
  "description": "An Ionic project",
  "cordova": {
    "plugins": {
      "cordova-plugin-x-toast": {},
      "onesignal-cordova-plugin": {},
      "cordova-plugin-camera": {},
      "cordova-plugin-ionic-keyboard": {},
      "cordova-plugin-file": {},
      "cordova-plugin-file-transfer": {},
      "cordova-plugin-file-opener2": {},
      "cordova-plugin-android-permissions": {},
      "cordova-plugin-telerik-imagepicker": {},
      "cordova-plugin-chooser": {},
      "cordova-plugin-app-version": {},
      "cordova-plugin-inappbrowser": {},
      "com-sarriaroman-photoviewer": {},
      "cordova-plugin-network-information": {},
      "cordova-plugin-whitelist": {},
      "cordova-plugin-statusbar": {},
      "cordova-plugin-device": {},
      "cordova-plugin-splashscreen": {},
      "cordova-plugin-ionic-webview": {
        "ANDROID_SUPPORT_ANNOTATIONS_VERSION": "27.+"
      }
    },
    "platforms": [
      "android",
      "ios"
    ]
  }
}
`

**Comment by tjoskar** [comment] 2020-03-27 16:29
Interesting that you are using Angular 8. This is, however, a duplicate of https://github.com/tjoskar/ng-lazyload-image/issues/441
I will close this.

**Closed by tjoskar** 2020-03-27 16:29 UTC
