### ISSUE TITLE
Can't bind to 'lazyLoad' since it isn't a known property of 'img'.

### ISSUE THREAD

**Issue by glenskie16** [tjoskar/ng-lazyload-image#406] opened 2019-09-04 19:07 UTC
Hello, I am trying to get lazyLoad to work on my Ionic 4 app. I have imported it on my app.module.ts, and are trying to use it on my page. I'm not sure what the issue is and any help is greatly appreciated.

app.module.ts
```ts
import { LazyLoadImageModule, intersectionObserverPreset } from 'ng-lazyload-image';

@NgModule({
  declarations: [AppComponent],
  entryComponents: [],
  imports: [
    BrowserModule,
    IonicModule.forRoot(),
    AppRoutingModule,
    HttpClientModule,
    IonicStorageModule.forRoot(),
    LazyLoadImageModule.forRoot({preset: intersectionObserverPreset})
  ],
  providers: [
    StatusBar,
    SplashScreen,
    Insomnia,
    { provide: RouteReuseStrategy, useClass: IonicRouteStrategy }
  ],
  bootstrap: [AppComponent]
})
export class AppModule {}
```

my page.html
```html
<ion-col size="2" *ngFor="let movie of browseResults| keyvalue">
  <div class="rating">&#9734; {{movie.value.rating}}</div>
  <img
    (click)="movieDetails(movie.value.stream_id)"
    (keyup.enter)="movieDetails(movie.value.stream_id)"
    [lazyLoad]="movie.value.stream_icon"
    class="browse-image focusable">
</ion-col>
```

And im importing it on the component.ts for this page but not sure what else to do. Its not really being used on the component.

**Comment by tjoskar** [comment] 2019-09-09 17:07
Hi,

Is there any chance you can create a small repo where you can reproduce the issue? Or is your code available on github?

**Comment by tjoskar** [comment] 2019-10-12 16:12
@glenskie16, did you solve this issue?
Are you using multiple `NgModule` or just one?

**Comment by msk286** [comment] 2019-12-09 16:46
@glenskie16 Most likely because you are using another module for your page. don't import LazyLoadImageModule into your AppModule, import it to your PageModule in order to make it work

**Comment by tjoskar** [comment] 2020-02-24 08:33
I'm closing this but let me know if this is still an issue.

**Closed by tjoskar** 2020-02-24 08:33 UTC

**Comment by digontobd** [comment] 2020-03-18 05:51
Hello,
I'm using ionic 4. I also have the same issue but after moving 'ng-lazyload-image' from app.module.ts to page module, the issue seems to be gone. But lazyload is not fired, default image is loading always. But when ionic infinite loaded triggered, first image is loaded only, rest are not. Can you please help me about that?

Angular CLI: 8.1.3
Node: 12.16.1
OS: win32 x64
Angular: 8.1.3
... cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.801.3
@angular-devkit/build-angular     0.801.3
@angular-devkit/build-optimizer   0.801.3
@angular-devkit/build-webpack     0.801.3
@angular-devkit/core              8.1.3
@angular-devkit/schematics        8.1.3
@ngtools/webpack                  8.1.3
@schematics/angular               8.1.3
@schematics/update                0.801.3
rxjs                              6.5.4
typescript                        3.4.5
webpack                           4.35.2

Thanks
