### ISSUE TITLE
Help me please error LazyLoadImageModule Please add @NgModule annotation !!!

### ISSUE THREAD

**Issue by thunyapk50** [tjoskar/ng-lazyload-image#226] opened 2017-11-12 13:06 UTC
Error: Unexpected value 'LazyLoadImageModule' imported by the module 'AppModule'. Please add a @NgModule annotation.
    at syntaxError (http://localhost:8100/build/vendor.js:81383:34)
    at http://localhost:8100/build/vendor.js:95236:44
    at Array.forEach (<anonymous>)
    at CompileMetadataResolver.getNgModuleMetadata (http://localhost:8100/build/vendor.js:95219:49)
    at JitCompiler._loadModules (http://localhost:8100/build/vendor.js:106654:70)
    at JitCompiler._compileModuleAndComponents (http://localhost:8100/build/vendor.js:106627:36)
    at JitCompiler.compileModuleAsync (http://localhost:8100/build/vendor.js:106556:37)
    at PlatformRef_._bootstrapModuleWithZone (http://localhost:8100/build/vendor.js:4894:25)
    at PlatformRef_.bootstrapModule (http://localhost:8100/build/vendor.js:4880:21)
    at Object.210 (http://localhost:8100/build/main.js:246:109)

**Comment by tjoskar** [comment] 2017-11-12 15:09
Yeah, `3.3.4` (latest) was a bad release. Try to downgrade to `3.3.3`. A new release is on its way.

Duplicate of: https://github.com/tjoskar/ng-lazyload-image/issues/222

**Closed by tjoskar** 2017-11-12 15:09 UTC

**Comment by thunyapk50** [comment] 2017-11-12 16:11
thank you very much. bro
