### ISSUE TITLE
Not working prod build with NG9

### ISSUE THREAD

**Issue by dozsan** [tjoskar/ng-lazyload-image#465] opened 2020-06-15 13:32 UTC
```
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 9.1.8
Node: 12.10.0
OS: linux x64

Angular: 9.1.11
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: No

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.8
@angular-devkit/build-angular     0.901.8
@angular-devkit/build-optimizer   0.901.8
@angular-devkit/build-webpack     0.901.8
@angular-devkit/core              9.1.8
@angular-devkit/schematics        9.1.8
@angular/cdk                      9.2.4
@angular/cli                      9.1.8
@angular/http                     7.2.16
@angular/material                 9.2.4
@ngtools/webpack                  9.1.8
@schematics/angular               9.1.8
@schematics/update                0.901.8
rxjs                              6.5.5
typescript                        3.9.5
webpack                           4.42.0
```
ng-lazyload-image version: ^8.0.1

ERROR in Error during template compile of 'AppModule'
  Function expressions are not supported in decorators in 'LazyLoadImageModule'
    'LazyLoadImageModule' contains the error at ../../../ng-lazyload-image/ng-lazyload-image.ts(22,23)
      Consider changing the function expression into an exported function.

**Comment by tjoskar** [comment] 2020-06-16 07:32
Hi,
Can you try to add:
```
"angularCompilerOptions": {
    "enableIvy": false
  }
```
In your `tsconfig.json` and `tsconfig.app.json` so they look something like:
tsconfig.json:
```
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "module": "esnext",
    "moduleResolution": "node",
    "importHelpers": true,
    "target": "es2015",
    "lib": [
      "es2018",
      "dom"
    ]
  },
  "angularCompilerOptions": {
    "fullTemplateTypeCheck": true,
    "strictInjectionParameters": true,
    "enableIvy": false
  }
}
```
tsconfig.app.json:
```
{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "outDir": "./out-tsc/app",
    "types": []
  },
  "files": [
    "src/main.ts",
    "src/polyfills.ts"
  ],
  "include": [
    "src/**/*.d.ts"
  ],
  "angularCompilerOptions": {
    "enableIvy": false
  }
}
```

**Comment by tjoskar** [comment] 2020-06-16 07:52
This looks like a duplicate of #463

**Closed by tjoskar** 2020-06-16 07:52 UTC
